// Vue.js+Vite.js/src/components/ButtonForm.vue
<script></script>

<template>
    <RouterLink to="/contact">
        <div alt="Formulário"></div>
    </RouterLink>
</template>

<style scoped>
    div {
        width: 82px; 
        height: 82px; 
        background-image: url(../assets/form.png); 
        margin-right: 7px; 
        transition: .25s;
        &:hover {
            background-image: url(../assets/form_on.png);
        }
    }
</style>

// React.js+Next.js/src/components/ButtonForm.jsx
'use client'

import React from "react";
import Link from 'next/link';

export default function ButtonForm()
{
  return (
    <>
      <Link href="/contact"><div alt="contato"></div></Link>

      <style jsx>{`
            div {
                width: 82px; 
                height: 82px; 
                background-image: url(/form.png); 
                margin-right: 7px; 
                transition: .25s;
                &:hover {
                    background-image: url(/form_on.png);
                }
            }
      `}</style>
    </>
  )
}
